[versions]
agp = "8.5.1"
dnsjava = "3.6.0"
kotlin = "2.0.0"
javaWebsocket = "1.5.6"
appcompat = "1.7.0"
sentryAndroid = "6.34.0"

[libraries]
dnsjava = { module = "dnsjava:dnsjava", version.ref = "dnsjava" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "javaWebsocket" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
sentry-android = { module = "io.sentry:sentry-android", version.ref = "sentryAndroid" }


[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

